// <auto-generated />
using System;
using HostCraft.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HostCraft.Infrastructure.Migrations
{
    [DbContext(typeof(HostCraftDbContext))]
    partial class HostCraftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HostCraft.Core.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalDomains")
                        .HasColumnType("text");

                    b.Property<bool>("AutoDeploy")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoDeployOnPush")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoRestart")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoRollback")
                        .HasColumnType("boolean");

                    b.Property<int?>("BackupRetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("BackupSchedule")
                        .HasColumnType("text");

                    b.Property<string>("BuildArgs")
                        .HasColumnType("text");

                    b.Property<string>("BuildContext")
                        .HasColumnType("text");

                    b.Property<string>("BuildSecrets")
                        .HasColumnType("text");

                    b.Property<string>("CertificateChallengePath")
                        .HasColumnType("text");

                    b.Property<bool>("CloneSubmodules")
                        .HasColumnType("boolean");

                    b.Property<int>("ConsecutiveHealthCheckFailures")
                        .HasColumnType("integer");

                    b.Property<long?>("CpuLimit")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DatabaseType")
                        .HasColumnType("integer");

                    b.Property<int>("DeploymentMode")
                        .HasColumnType("integer");

                    b.Property<int>("DeploymentStrategy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DockerBuildTarget")
                        .HasColumnType("text");

                    b.Property<string>("DockerComposeFile")
                        .HasColumnType("text");

                    b.Property<string>("DockerImage")
                        .HasColumnType("text");

                    b.Property<string>("Dockerfile")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<bool>("EnableGitLfs")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableHttps")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnablePreviewDeployments")
                        .HasColumnType("boolean");

                    b.Property<bool>("ForceHttps")
                        .HasColumnType("boolean");

                    b.Property<string>("GitBranch")
                        .HasColumnType("text");

                    b.Property<string>("GitOwner")
                        .HasColumnType("text");

                    b.Property<int?>("GitProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("GitRepoName")
                        .HasColumnType("text");

                    b.Property<string>("GitRepository")
                        .HasColumnType("text");

                    b.Property<int>("HealthCheckIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("HealthCheckTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("HealthCheckUrl")
                        .HasColumnType("text");

                    b.Property<string>("LastCommitMessage")
                        .HasColumnType("text");

                    b.Property<string>("LastCommitSha")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastDeployedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastHealthCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LetsEncryptEmail")
                        .HasColumnType("text");

                    b.Property<int>("MaxConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPreviewDeployments")
                        .HasColumnType("integer");

                    b.Property<long?>("MemoryLimitBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("PortMappings")
                        .HasColumnType("text");

                    b.Property<string>("PreviewLabels")
                        .HasColumnType("text");

                    b.Property<string>("PreviewUrlTemplate")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("PublishedPort")
                        .HasColumnType("integer");

                    b.Property<string>("RegistryPassword")
                        .HasColumnType("text");

                    b.Property<string>("RegistryServer")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RegistryUsername")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Replicas")
                        .HasColumnType("integer");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("SwarmEndpointSpec")
                        .HasColumnType("text");

                    b.Property<string>("SwarmMode")
                        .HasColumnType("text");

                    b.Property<string>("SwarmNetworks")
                        .HasColumnType("text");

                    b.Property<int>("PlacementStrategy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SwarmPlacementConstraints")
                        .HasColumnType("text");

                    b.Property<string>("SwarmPlacementPreferences")
                        .HasColumnType("text");

                    b.Property<int?>("MaxReplicasPerNode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("SwarmReplicas")
                        .HasColumnType("integer");

                    b.Property<string>("SwarmRollbackConfig")
                        .HasColumnType("text");

                    b.Property<string>("SwarmServiceId")
                        .HasColumnType("text");

                    b.Property<long?>("SwarmStopGracePeriod")
                        .HasColumnType("bigint");

                    b.Property<string>("SwarmUpdateConfig")
                        .HasColumnType("text");

                    b.Property<string>("TraefikLabelOverrides")
                        .HasColumnType("text");

                    b.Property<bool>("UsePrivateRegistry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("UseSharedStorage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("VolumeDriver")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("local");

                    b.Property<string>("VolumeDriverOptions")
                        .HasColumnType("text");

                    b.Property<string>("WatchPaths")
                        .HasColumnType("text");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GitProviderId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("ServerId", "Name")
                        .IsUnique();

                    b.HasIndex("ServerId", "PublishedPort")
                        .IsUnique()
                        .HasFilter("\"PublishedPort\" IS NOT NULL");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("IsSuccess");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Backup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<int?>("BackupConfigurationId")
                        .HasColumnType("integer");

                    b.Property<string>("Checksum")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompressed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ManifestJson")
                        .HasColumnType("text");

                    b.Property<int>("ProjectCount")
                        .HasColumnType("integer");

                    b.Property<string>("RemoteStoragePath")
                        .HasColumnType("text");

                    b.Property<int?>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("S3Bucket")
                        .HasColumnType("text");

                    b.Property<string>("S3Key")
                        .HasColumnType("text");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int>("ServerCount")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("VolumeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("BackupConfigurationId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("VolumeId");

                    b.HasIndex("ApplicationId", "Status", "StartedAt");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.BackupConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoBackupEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("AutoBackupSchedule")
                        .HasColumnType("text");

                    b.Property<int>("AutoBackupScope")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableCompression")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableEncryption")
                        .HasColumnType("boolean");

                    b.Property<string>("EncryptionKey")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastBackupAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderConfiguration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.Property<bool>("VerifyAfterUpload")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("BackupConfigurations");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Issuer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRenewalAttempt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RenewalDays")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.ComposeEnvironmentVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ComposeEnvironmentVariables");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.DatabaseTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultEnvironmentVariables")
                        .HasColumnType("text");

                    b.Property<int>("DefaultPort")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultVolumePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DockerImage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HealthCheckCommand")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("RecommendedCpuLimit")
                        .HasColumnType("double precision");

                    b.Property<long?>("RecommendedMemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("DatabaseTemplates", (string)null);
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Deployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("CommitAuthor")
                        .HasColumnType("text");

                    b.Property<string>("CommitHash")
                        .HasColumnType("text");

                    b.Property<string>("CommitMessage")
                        .HasColumnType("text");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text");

                    b.Property<string>("ContainerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageDigest")
                        .HasColumnType("text");

                    b.Property<string>("ImageTag")
                        .HasColumnType("text");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("boolean");

                    b.Property<string>("PreviewId")
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Status");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "StartedAt");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.DeploymentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeploymentId")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("DeploymentId", "Timestamp");

                    b.ToTable("DeploymentLogs");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<bool>("BasicAuthEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("BasicAuthUsers")
                        .HasColumnType("text");

                    b.Property<int?>("CertificateId")
                        .HasColumnType("integer");

                    b.Property<string>("CertificateType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("letsencrypt");

                    b.Property<bool>("CompressionEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("text");

                    b.Property<string>("DnsError")
                        .HasColumnType("text");

                    b.Property<string>("DnsStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending");

                    b.Property<bool>("ForceHttps")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("HttpsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("IpWhitelist")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDnsCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxBodySizeMb")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("/");

                    b.Property<bool>("PathBasedRouting")
                        .HasColumnType("boolean");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("ProxyProtocol")
                        .HasColumnType("integer");

                    b.Property<int>("RateLimitRps")
                        .HasColumnType("integer");

                    b.Property<bool>("StripPathPrefix")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("WebSocketEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("Host", "Path")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "IsPrimary", "Host");

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.EnvironmentVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Key")
                        .IsUnique();

                    b.ToTable("EnvironmentVariables");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.GitProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApiUrl")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GitProviders");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.GitProviderSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUrl")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Type", "ApiUrl")
                        .IsUnique();

                    b.ToTable("GitProviderSettings");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.HealthCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CheckedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<int?>("ServerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CheckedAt");

                    b.HasIndex("ServerId");

                    b.HasIndex("ApplicationId", "CheckedAt");

                    b.ToTable("HealthChecks");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.PrivateKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("KeyData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Passphrase")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PrivateKeys");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.RestoreOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationsRestored")
                        .HasColumnType("integer");

                    b.Property<int>("BackupId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ProgressLog")
                        .HasColumnType("text");

                    b.Property<int>("ProjectsRestored")
                        .HasColumnType("integer");

                    b.Property<string>("RestoreMappingJson")
                        .HasColumnType("text");

                    b.Property<int>("RestoreScope")
                        .HasColumnType("integer");

                    b.Property<int>("ServersRestored")
                        .HasColumnType("integer");

                    b.Property<string>("SkippedItems")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Strategy")
                        .HasColumnType("integer");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BackupId");

                    b.ToTable("RestoreOperations");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualHostname")
                        .HasColumnType("text");

                    b.Property<string>("AvailabilityZone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Datacenter")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DefaultLetsEncryptEmail")
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsSwarmManager")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSwarmWorker")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWizardSetup")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int?>("PrivateKeyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProxyDeployedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProxyType")
                        .HasColumnType("integer");

                    b.Property<string>("ProxyVersion")
                        .HasColumnType("text");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SwarmAdvertiseAddress")
                        .HasColumnType("text");

                    b.Property<string>("SwarmId")
                        .HasColumnType("text");

                    b.Property<string>("SwarmJoinToken")
                        .HasColumnType("text");

                    b.Property<string>("SwarmManagerAddress")
                        .HasColumnType("text");

                    b.Property<int?>("SwarmManagerCount")
                        .HasColumnType("integer");

                    b.Property<string>("SwarmNodeAvailability")
                        .HasColumnType("text");

                    b.Property<string>("SwarmNodeId")
                        .HasColumnType("text");

                    b.Property<string>("SwarmNodeState")
                        .HasColumnType("text");

                    b.Property<int?>("SwarmWorkerCount")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("WizardCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WizardStep")
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("WizardCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WizardStep")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PrivateKeyId");

                    b.HasIndex("RegionId");

                    b.HasIndex("Host", "Port")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CertificateStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ConfiguredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("HostCraftApiDomain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HostCraftDomain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("HostCraftEnableHttps")
                        .HasColumnType("boolean");

                    b.Property<string>("HostCraftLetsEncryptEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("JwtAudience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JwtExpirationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("JwtIssuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JwtSecret")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProxyUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TraefikDashboardAuthEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TraefikDashboardDomain")
                        .HasColumnType("text");

                    b.Property<string>("TraefikDashboardPasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("TraefikDashboardUsername")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPasswordChangeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecoveryCodes")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("text");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Volume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("BackupSchedule")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Driver")
                        .HasColumnType("text");

                    b.Property<bool>("IsBackedUp")
                        .HasColumnType("boolean");

                    b.Property<string>("MountPoint")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("ServerId", "Name")
                        .IsUnique();

                    b.ToTable("Volumes");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Application", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.GitProvider", "GitProvider")
                        .WithMany("Applications")
                        .HasForeignKey("GitProviderId");

                    b.HasOne("HostCraft.Core.Entities.Project", "Project")
                        .WithMany("Applications")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HostCraft.Core.Entities.Server", "Server")
                        .WithMany("Applications")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GitProvider");

                    b.Navigation("Project");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Backup", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.Application", "Application")
                        .WithMany("Backups")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HostCraft.Core.Entities.BackupConfiguration", "BackupConfiguration")
                        .WithMany("Backups")
                        .HasForeignKey("BackupConfigurationId");

                    b.HasOne("HostCraft.Core.Entities.Volume", null)
                        .WithMany("Backups")
                        .HasForeignKey("VolumeId");

                    b.Navigation("Application");

                    b.Navigation("BackupConfiguration");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Certificate", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.Application", "Application")
                        .WithMany("Certificates")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.ComposeEnvironmentVariable", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.Application", "Application")
                        .WithMany("ComposeVariables")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Deployment", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.Application", "Application")
                        .WithMany("Deployments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.DeploymentLog", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.Deployment", "Deployment")
                        .WithMany("Logs")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Domain", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.Application", "Application")
                        .WithMany("Domains")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HostCraft.Core.Entities.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Application");

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.EnvironmentVariable", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.Application", "Application")
                        .WithMany("EnvironmentVariables")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.GitProvider", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.HealthCheck", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.Application", "Application")
                        .WithMany("HealthChecks")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HostCraft.Core.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Application");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.RestoreOperation", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.Backup", "Backup")
                        .WithMany()
                        .HasForeignKey("BackupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Backup");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Server", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.PrivateKey", "PrivateKey")
                        .WithMany("Servers")
                        .HasForeignKey("PrivateKeyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HostCraft.Core.Entities.Region", "Region")
                        .WithMany("Servers")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrivateKey");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Volume", b =>
                {
                    b.HasOne("HostCraft.Core.Entities.Application", "Application")
                        .WithMany("Volumes")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HostCraft.Core.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Application", b =>
                {
                    b.Navigation("Backups");

                    b.Navigation("Certificates");

                    b.Navigation("ComposeVariables");

                    b.Navigation("Deployments");

                    b.Navigation("Domains");

                    b.Navigation("EnvironmentVariables");

                    b.Navigation("HealthChecks");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.BackupConfiguration", b =>
                {
                    b.Navigation("Backups");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Deployment", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.GitProvider", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.PrivateKey", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Project", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Region", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Server", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("HostCraft.Core.Entities.Volume", b =>
                {
                    b.Navigation("Backups");
                });
#pragma warning restore 612, 618
        }
    }
}
